### PR TITLE
Bug/save vertex shape

### LINKED ISSUE #383: Include Shape in SaveLoad interface
**Describe the bug**
I have a vertex whose shape I define manually. This allows me to do a correct matrix multiplication when I define my Bayesian Network. Unfortunately, shape information is not stored in the protobuf saved version so when I save and load my graph, I get an error because the matrix multiplication doesn't like the shape of my vertex.

**Expected behavior**
I would like to be able to save and load Bayesian Networks which include vertices that are reliant on shape information without getting errors.

### PR DESCRIPTION
**Pull request by christophernorth**
The shapes for all vertices are now saved to the protobuf
Updated constructor annotations for all vertices that take an explicit shape so they can be constructed with the shape from the protobuf.
Added test case that covers the initial problem.
Resolves #383

### CODE REVIEW

File: keanu-project/src/test/java/io/improbable/keanu/network/ProtobufTest.java [hunk 1]
```diff
@@ -458,12 +475,17 @@ private void checkSaveableVertex(Class<? extends Vertex> vertexClass) {
...
+            LoadVertexParam parameterAnnotation = parameter.getAnnotation(LoadVertexParam.class);
+            LoadShape shapeAnnotation = parameter.getAnnotation(LoadShape.class);
+            assertThat("Annotation has to be present on all Constructor params for class: " + vertexClass,
+                parameterAnnotation != null || shapeAnnotation != null);
+            if (parameterAnnotation != null) {
+                assertThat("Annotation can only be used once for class: " + vertexClass, requiredParameters,
+                    not(hasKey(parameterAnnotation.value())));
+                requiredParameters.put(parameterAnnotation.value(), parameter.getType());
+            } else {
+                assertThat("Shape Arguments must be long[]", parameter.getType().isAssignableFrom(long[].class));
```
Comment (wesleyw72) [inline keanu-project/src/test/java/io/improbable/keanu/network/ProtobufTest.java]: The name of this method (`getRequiredParamsAndCheckOnlyUsedOnce`) doesn't make it that clear to me that anything is being done with the shape annotation. Is there a way we could either make that more clear or split it out from here?

File: keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/SmoothUniformVertex.java [hunk 2]
```diff
@@ -107,7 +106,9 @@ public SmoothUniformVertex(long[] tensorShape, double xMin, double xMax, double
         this(tensorShape, new ConstantDoubleVertex(xMin), new ConstantDoubleVertex(xMax), edgeSharpness);
     }
 
-    public SmoothUniformVertex(long[] tensorShape, DoubleVertex xMin, DoubleVertex xMax) {
+    public SmoothUniformVertex(@LoadShape long[] tensorShape,
```
[the remark this answers is not in the document]
Comment (christophernorth) [reply keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/SmoothUniformVertex.java]: 👍

File: keanu-project/src/test/java/io/improbable/keanu/network/ProtobufTest.java [hunk 3]
```diff
@@ -94,6 +94,23 @@ public void youCanSaveAndLoadANetworkWithValues() throws IOException {
...
+        BayesianNetwork bayesNet = new BayesianNetwork(output.getConnectedGraph());
+
+        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
+        ProtobufSaver saver = new ProtobufSaver(bayesNet);
+        saver.save(outputStream, false);
+
+        ByteArrayInputStream inputStream = new ByteArrayInputStream(outputStream.toByteArray());
+        ProtobufLoader loader = new ProtobufLoader();
+
+        BayesianNetwork readNet = loader.loadNetwork(inputStream);
```
[the remark this answers is not in the document]
Comment (christophernorth) [reply keanu-project/src/test/java/io/improbable/keanu/network/ProtobufTest.java]: I left that implicit as the shapes have to be "correct" due to the matrix multiply (as in that will assert if they're wrong).  I can add in an explicit check though as well.

File: keanu-project/src/test/java/io/improbable/keanu/network/ProtobufTest.java (hunk 1 above)
Comment (christophernorth) [reply keanu-project/src/test/java/io/improbable/keanu/network/ProtobufTest.java]: Renamed the function

File: keanu-project/src/main/java/io/improbable/keanu/network/ProtobufLoader.java [hunk 4]
```diff
@@ -213,13 +205,39 @@ private Vertex instantiateVertex(Class vertexClass,
...
+                                KeanuSavedBayesNet.Vertex vertex) {
+        LoadVertexParam paramAnnotation;
+        LoadShape shapeAnnotation;
+
+        if ((paramAnnotation = methodParameter.getAnnotation(LoadVertexParam.class)) != null) {
+            Object parameter = paramMap.get(paramAnnotation.value());
+            if (parameter == null) {
+                throw new IllegalArgumentException("Failed to create vertex due to missing parent: "
+                    + paramAnnotation.value());
+            }
```
Comment (migwellian) [inline keanu-project/src/main/java/io/improbable/keanu/network/ProtobufLoader.java]: for consistency (with line 224) I think you should put an `else` here

File: keanu-project/src/main/java/io/improbable/keanu/network/ProtobufLoader.java [hunk 5]
```diff
@@ -213,13 +205,39 @@ private Vertex instantiateVertex(Class vertexClass,
...
+            return parameter;
+        } else if ((shapeAnnotation = methodParameter.getAnnotation(LoadShape.class)) != null) {
```
Comment (migwellian) [inline keanu-project/src/main/java/io/improbable/keanu/network/ProtobufLoader.java]: `shapeAnnotation` is never used

File: keanu-project/src/test/java/io/improbable/keanu/network/ProtobufTest.java [hunk 6]
```diff
@@ -94,6 +94,23 @@ public void youCanSaveAndLoadANetworkWithValues() throws IOException {
         latentGaussianVertex.sample();
     }
 
+    @Test
```
Comment (migwellian) [inline keanu-project/src/test/java/io/improbable/keanu/network/ProtobufTest.java]: Do you need to add some tests for failure cases relating to shape? Similar to your other `loadFailsIf...` tests.

File: keanu-project/src/main/java/io/improbable/keanu/network/ProtobufLoader.java (hunk 4 above)
Comment (christophernorth) [reply keanu-project/src/main/java/io/improbable/keanu/network/ProtobufLoader.java]: Fixed

File: keanu-project/src/main/java/io/improbable/keanu/network/ProtobufLoader.java (hunk 5 above)
Comment (christophernorth) [reply keanu-project/src/main/java/io/improbable/keanu/network/ProtobufLoader.java]: Yeah - I just added it for consistency with the paramAnnotation case.  I guess it's not required - I'll remove.

File: keanu-project/src/test/java/io/improbable/keanu/network/ProtobufTest.java (hunk 6 above)
Comment (christophernorth) [reply keanu-project/src/test/java/io/improbable/keanu/network/ProtobufTest.java]: There isn't really a failure case for shape - it can happily be left out entirely from the protobuf ( in fact that's what happens for scalars anyway).
